# Generated by Django 2.2.6 on 2020-05-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publish',
            old_name='category',
            new_name='categories',
        ),
    ]
