# Generated by Django 2.2.6 on 2020-05-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0002_auto_20200503_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
